### ISSUE TITLE
Unable to load integration

### ISSUE THREAD

**Issue by PeterChia604** [qqaatw/JciHitachiHA#13]
For the last two days, been getting an error, indicating the Integration plug-in did not start.
Tried to restart, then reload & restart but did not work at all.  The issue is persistent.

Any thoughts on how to fix?

Logger: homeassistant.setup
Source: setup.py:155
First occurred: 21:37:06 (1 occurrences)
Last logged: 21:37:06
Setup failed for jcihitachi_tw: Requirements for jcihitachi_tw not found: ['LibJciHitachi==0.4.6'].

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 21:36:44 (3 occurrences)
Last logged: 21:37:06
Unable to install package LibJciHitachi==0.4.6: ERROR: Cannot install libjcihitachi==0.4.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Errors:
![image](https://user-images.githubusercontent.com/95140180/156576283-3bab962a-9861-426b-b249-f7d4a1162148.png)
![image](https://user-images.githubusercontent.com/95140180/156576560-e526814c-f015-4bee-90fd-fef2bd44c203.png)
![image](https://user-images.githubusercontent.com/95140180/156576641-0a6d2087-043b-4362-b134-49ddee8bbd75.png)

System config:
![image](https://user-images.githubusercontent.com/95140180/156577274-7a3b5061-ccc5-47cc-aa91-3639e512c4ed.png)

**Comment by PeterChia604** [comment]
I've also manually installed the library as indicated on https://github.com/qqaatw/LibJciHitachi
Still unable to resolve.

**Comment by qqaatw** [comment]
See `v0.2.6`

**Comment by PeterChia604** [comment]
Did the update and restarted.  Different error message now.
Then I removed (deleted) the integration and added it back in (relogin to the hitachi account) but still get the new message.
Restarted HA, same.

![image](https://user-images.githubusercontent.com/95140180/156614746-a552ecf5-b9c1-440d-b5b6-7a345a1e9443.png)
![image](https://user-images.githubusercontent.com/95140180/156614811-dba4aab8-b78f-4b70-a598-0d4b4ac2455a.png)

**Comment by qqaatw** [comment]
Problem seemed from HITACHI side. The CI also failed three hours ago at the first test attempt.

https://github.com/qqaatw/LibJciHitachi/runs/5408669537?check_suite_focus=true

**Comment by immelmanchen** [comment]
Yesterday, I have same problem when upgrade core-2022.3.0.
Today. I downgrade to core-2022.2.9, the problem has not happen.

**Comment by xzero0911** [comment]
Same here.
I just upgrade to core 2022.3.0 and can not load issue happened.

**Comment by qqaatw** [comment]
@immelmanchen @xzero0911 - `v0.2.6` should fix the problem, please upgrade and try again.

**Comment by xzero0911** [comment]
![圖片](https://user-images.githubusercontent.com/38142609/156930134-f87cf874-421a-40db-a4d5-0877db0e620b.png)

Thank you for your reply.
After upgrade integration to v0.2.6 and got this new error here.

**Comment by qqaatw** [comment]
@xzero0911 As I said, the recently occurring problem `Failed to login API` was from Hitachi's side. This problem, which is home assistant version agnostic, also randomly failed our CI [1] a few days ago. You can take a look at the reviews [2] from Google Play, some people have reported that recently.

[1] https://github.com/qqaatw/LibJciHitachi/runs/5408669537?check_suite_focus=true
[2] https://play.google.com/store/apps/details?id=com.hitachi.TaiSEIA.smarthome&hl=zh_TW&gl=US&showAllReviews=true

**Comment by xzero0911** [comment]
@qqaatw 
Fully understand with thanks!
I will waiting HITACHI side to resolve this error.

**Comment by immelmanchen** [comment]
@qqaatw 
After I upgraded to v0.2.6, but the issue still happened.
![SmartSelect_20220307-091619_Home Assistant](https://user-images.githubusercontent.com/30484059/156951983-37f3e4b6-66f5-450b-b7c0-38a549890346.jpg)
![SmartSelect_20220307-091559_Home Assistant](https://user-images.githubusercontent.com/30484059/156951986-e88681e8-e535-4137-884c-b4c3ead2dc29.jpg)

**Comment by qqaatw** [comment]
@immelmanchen - From the picture provided, it looks that the integration wasn't upgraded at all.

**Comment by xzero0911** [comment]
@qqaatw 
Thanks for kindly help, 
I confirm HITACH side resolved API login issue in this morning.
Device in HA also works well again.

To whom have same issue.
If still not works,
Your HITACHI device and HA should need to fully restart once.
Specs in my case.
HA core 2022.3.1
HA OS 7.2
JciHitachiHA v0.2.6

**Comment by PeterChia604** [comment]
I am still having issues, now it is a little different.
![image](https://user-images.githubusercontent.com/95140180/157074403-dd9ad3e8-0f62-4c3d-862b-2db24743b25b.png)
![image](https://user-images.githubusercontent.com/95140180/157073806-a1a4e7d6-eb79-4547-b817-f5c8740d065f.png)

My system has been updated to core-2022.3.2
![image](https://user-images.githubusercontent.com/95140180/157074280-1ae5dfeb-813a-4df3-89fa-2ff7adf45a67.png)

I had deleted the integration from Configuration-> Devices&Services -> JciHitachi TW , restart, reinstall, restart.  Same error.
I had deleted the integration from HACS, restart, re-install from HACS, restart, From Configuration-> Devices&Services -> add 
 JciHitachi TW.  The initial login is fine.  It accepts the account/password and proceeds.  but same error message.

login is fine:
![image](https://user-images.githubusercontent.com/95140180/157075788-a5f268f4-2b34-415c-8a39-452a5da21249.png)

**Comment by immelmanchen** [comment]
@qqaatw 
Thank for your reply,
I try to upgrade v0.2.6 again and my core is 2022.3.2
Now JciHitachi is working well.
Thank you for your help.

**Comment by qqaatw** [comment]
@PeterChia604 - 

Using HACS or not doesn't matter I believe, though it wasn't tested before.

One important point needed to be clarified is that passing credential verification doesn't mean device statuses retrieved successfully as they use different protocol to connect.

The login verification and device list retrieval use http-based connection, which work 99% time without problem. On the other hand, the support and status code retrieval uses mqtt-based connection, which seems not optimized well and thereby has issues sometimes.

If the app cannot connect to the device, this integration will not work either. No magic inside the integration.

**Comment by AaronFUFU** [comment]
型號：RD-240HH
重啟ＨＡ後時常讀取不到設備，會顯示Failed to login API。

**Comment by qqaatw** [comment]
Hey @AaronFUFU, I haven't encountered this issue recently. Would be helpful if you provide the logs showing the error `Failed to login API`.

**Comment by qqaatw** [comment]
Closing as no further discussion is proposed.

**Comment by PeterChia604** [comment]
Just wanted to close this.  This is now fix.  The issue was nothing from this Integration.  
Updated to Home Assistant 2022.4.2 & Supervisor Version to 2022.04.0

After reboot, the JciHitachiHA worked fine.   :-)
![image](https://user-images.githubusercontent.com/95140180/162768926-f0fc9c6d-d00a-4714-bbfd-400a00e55849.png)
